# Generated by Django 5.0.4 on 2024-04-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_image_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_filter',
        ),
    ]
